gest_bib_lib/gestion/bibliotheque/urls.py
from django.urls import path
from . import views

app_name = "bibliotheque"

urlpatterns = [
    path('', views.index, name='index'),
    path('bibliotheque', views.bibliotheque, name='bibliotheque'),
    path('<int:id>/', views.livre, name='livre'),
]

gest_bib_lib/gestion/gestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("bibliotheque.urls"))
]

gest_bib_lib/gestion/bibliotheque/models.py
from django.db import models

# Create your models here.

class Categories(models.Model):
    
    lib_cat = models.CharField(max_length = 70, unique = True, verbose_name = "Libellé")
    code_cat = models.CharField(max_length = 30, unique = True, verbose_name = "Code Catégorie")
    def __str__(self):
        return self.lib_cat
    
    class Meta():
        verbose_name = "Categorie"
        verbose_name_plural = "Categories"
        
class Autheur(models.Model):
    coor_aut = models.CharField(max_length = 100, unique = True, verbose_name ="Nom Prénom auteur")
    
    
    def __str__(self):
        return self.coor_aut
    
    class Meta():
        verbose_name = "Auteur"
        verbose_name_plural = "Auteurs"
        
class LivreBibliotheque(models.Model):
    id_livre = models.IntegerField( unique = True, primary_key = True, verbose_name="id", auto_created=True)
    titre = models.CharField(max_length=255, verbose_name="Titre")
    descriptions = models.CharField(verbose_name = "Description", max_length=255)
    date_sortie = models.DateField(verbose_name="Date de sortie")
    nbr_lecture = models.IntegerField(verbose_name="Nombre de lecture au total")
    auteur = models.ForeignKey(Autheur, on_delete=models.DO_NOTHING, verbose_name="Autheur")
    catego = models.ForeignKey(Categories, on_delete=models.DO_NOTHING, verbose_name="Categorie")
    def __str__(self):
        return self.titre
    
    class Meta():
        verbose_name="Livre"
        verbose_name_plural="Livres"
    

gest_bib_lib/gestion/librairie/models.py
from django.db import models

# Create your models here.

gest_bib_lib/gestion/bibliotheque/views.py
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404
from .models import Categories, LivreBibliotheque, Autheur
# Create your views here.

def index(request):
    context = {
        "name":"valeur",
        
    }
    
    return render(request, "bibliotheque/index.html", context)

def bibliotheque(request):
    context = {
        "recup":LivreBibliotheque.objects.all(),
    }
    return render(request, "bibliotheque/bibi.html", context)

def livre(request, id):
    context = {
        "livre":get_object_or_404(LivreBibliotheque, pk=id)
    }
    
    return render(request, "bibliotheque/livre.html", context)

gest_bib_lib/gestion/librairie/views.py
from django.shortcuts import render

# Create your views here.

gest_bib_lib/gestion/bibliotheque/templates/bibliotheque/bibi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Xtra Blog</title>
	<link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}"> <!-- https://fontawesome.com/ -->
	
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href=" {% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">
<!--
    
TemplateMo 553 Xtra Blog

https://templatemo.com/tm-553-xtra-blog

-->
</head>
<body>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
                        <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>                                
                    </form>
                </div>                
            </div>        
            <div class="row tm-row">
                {% for recups in recup %}
                    <article class="col-12 col-md-6 tm-post" id="con">
                        <hr class="tm-hr-primary">
                        <a href="{% url 'bibliotheque:livre' recups.id_livre %}" class="effect-lily tm-post-link tm-pt-60">
                            <div class="tm-post-link-inner">
                                <!--<img src="img/img-01.jpg" alt="Image" class="img-fluid">                           --> 
                            </div>
                            <span class="position-absolute tm-new-badge">LIRE</span>
                            <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ recups.titre }}</h2>
                        </a>                    
                        <p class="tm-pt-30">
                            {{ recups.descriptions }} 
                        </p>
                        <div class="d-flex justify-content-between tm-pt-45">
                            <span class="tm-color-primary">
                                {% if recups.nbr_lecture <= 1 %}
                                    {{recups.nbr_lecture}} lecture
                                {% else %}
                                    {{recups.nbr_lecture}} Lectures
                                {% endif %}
                            </span>
                            <span class="tm-color-primary">Depuis le {{ recups.date_sortie }}</span>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between">
                            <span>{{ recups.auteur }}</span>
                            <span>{{ recups.catego }}</span>
                        </div>
                    </article>
                {% endfor %}
                <!-- <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="post.html" class="effect-lily tm-post-link tm-pt-60">
                        <div class=" tm-post-link-inner">
                            <img src="img/img-02.jpg" alt="Image" class="img-fluid">                          
                        </div>
                        <span class="position-absolute tm-new-badge">LIBRAIRIE</span>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">Achetez ou payez des livres en ligne</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        Besoin d'achetez un livre sans pour autant vous déplacez a chercher une librairie, super vous êtes au bon
                        endroits. Choisissez celui ou ceux qui conviennent, payer et lisez en toute tanquilité
                    </p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">Mise à jour le  </span>
                        <span class="tm-color-primary">{% now "d/m/y" %} à {% now "h:i:s" %}</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>54 Livres au total</span>
                        <span>Admin</span>
                    </div>

                
                </article>
                <div>
                    {% for recups in recup%}

                    <li>{{ recups.auteur }}</li>
                    <li>{{ recups.catego }}</li>
                    {% endfor %}
                </div>
                
                <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="post.html" class="effect-lily tm-post-link tm-pt-20">
                        <div class="tm-post-link-inner">
                            <img src="img/img-03.jpg" alt="Image" class="img-fluid">
                        </div>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">How can you apply Xtra Blog</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        You are <u>allowed</u> to convert this template as any kind of CMS theme or template for your custom website builder. 
                        You can also use this for your clients. Thank you for choosing us.
                    </p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">Music . Audio</span>
                        <span class="tm-color-primary">June 11, 2020</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>24 comments</span>
                        <span>by John Walker</span>
                    </div>
                </article>
                <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="post.html" class="effect-lily tm-post-link tm-pt-20">
                        <div class="tm-post-link-inner">
                            <img src="img/img-04.jpg" alt="Image" class="img-fluid">
                        </div>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">A little restriction to apply</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        You are <u>not allowed</u> to re-distribute this template as a downloadable ZIP file on any template collection
                        website. This is strongly prohibited as we worked hard for this template. Please contact TemplateMo for more information.
                		<br>For example, <a href="https://www.free-css.com/free-css-templates/page272/xtra-blog" target="_blank">Free-CSS</a> redistributed this Xtra Blog template on their website without asking any permission. It is an illegal act by Free-CSS website doing an unauthorized reposting.</p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">Artworks . Design</span>
                        <span class="tm-color-primary">June 4, 2020</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>72 comments</span>
                        <span>by Admin Sam</span>
                    </div>
                </article>
                <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="post.html" class="effect-lily tm-post-link tm-pt-20">
                        <div class="tm-post-link-inner">
                            <img src="img/img-05.jpg" alt="Image" class="img-fluid">
                        </div>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">Color hexa values of Xtra Blog</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        If you wish to kindly support us, please contact us or contribute a small PayPal amount to info [at] templatemo.com that is helpful for us.
                        <br>
                        Title #099 New #0CC <br>
                        <span class="tm-color-primary">Text #999 Line #CCC Next #0CC Prev #F0F0F0</span>
                    </p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">Creative . Video . Audio</span>
                        <span class="tm-color-primary">May 31, 2020</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>84 comments</span>
                        <span>by Admin Sam</span>
                    </div>
                </article>
                <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="post.html" class="effect-lily tm-post-link tm-pt-20">
                        <div class="tm-post-link-inner">
                            <img src="img/img-06.jpg" alt="Image" class="img-fluid">
                        </div>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">Donec convallis varius risus</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        Quisque id ipsum vel sem maximus vulputate sed quis velit. Nunc vel turpis eget orci elementum cursus vitae in eros. Quisque vulputate nulla ut dolor consectetur luctus.
                    </p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">Visual . Artworks</span>
                        <span class="tm-color-primary">June 16, 2020</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>96 comments</span>
                        <span>by Admin Sam</span>
                    </div>
                </article>
            -->
            </div>
            
            <div class="row tm-row tm-mt-100 tm-mb-75">
                <div class="tm-prev-next-wrapper">
                    <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
                    <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
                </div>
                <div class="tm-paging-wrapper">
                    <span class="d-inline-block mr-3">Page</span>
                    <nav class="tm-paging-nav d-inline-block">
                        <ul>
                            <li class="tm-paging-item active">
                                <a href="#" class="mb-2 tm-btn tm-paging-link">1</a>
                            </li>
                            <li class="tm-paging-item">
                                <a href="#" class="mb-2 tm-btn tm-paging-link">2</a>
                            </li>
                            <li class="tm-paging-item">
                                <a href="#" class="mb-2 tm-btn tm-paging-link">3</a>
                            </li>
                            <li class="tm-paging-item">
                                <a href="#" class="mb-2 tm-btn tm-paging-link">4</a>
                            </li>
                        </ul>
                    </nav>
                </div>                
            </div>            
            <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Tout droits réservé: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">Roche &copy;</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Marques déposé 
                </div>
            </footer>
        </main>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/templatemo-script.js' }"></script>
</body>
</html>

gest_bib_lib/gestion/bibliotheque/templates/bibliotheque/livre.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ livre.descriptions }} 

    {{ livre.auteur }}
</body>
</html>