tp/1/first/first/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manga/', include('mangalib.urls')),
]

tp/1/first/mangalib/urls.py
from django.urls import path
from . import views

app_name = "mangalib"

urlpatterns  = [
    path('',views.index, name='index'), 
    
    path('<int:book_id>/', views.show, name='show'),
    
    path('ajouter-livre/', views.add, name='add')
]

tp/1/first/mangalib/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="Nom")
    
    def __str__(self):
        return self.name
        # renvoie le nom de chaque autheur au lieu de l'objet
    
    class Meta():
        verbose_name = "Auteur"
        verbose_name_plural = "Auteurs"
        
    
class Book(models.Model):
        title = models.CharField(max_length=32, unique = True, verbose_name="Titre")
        quantity = models.IntegerField(default=1, verbose_name="Quantité")
        author = models.ForeignKey(Author, on_delete=models.DO_NOTHING, verbose_name="Auteur")
        
        def __str__(self):
            return self.title
        
        class Meta:
            verbose_name = "Livre"
            verbose_name_plural = "Livres"

tp/1/first/mangalib/forms.py
from django import forms

class SomeForm(forms.Form):
    username = forms.CharField(max_length=45, label="Nom d'utilisateur")
    
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
    
    bio = forms.CharField(label="Biographie", widget=forms.Textarea)
    

    publicate = forms.CheckboxInput()
    
    

tp/1/first/mangalib/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
#from django.template import loader
from .models import Book, Author
# Create your views here.

from .forms import SomeForm

def index(request):
    #return HttpResponse("<p style=color:red;>Bienvenue sur Managlib ! </p><br>")
    
    
    if request.method == 'POST':
        form = SomeForm(request.POST)
        if form.is_valid():
            return redirect("mangalib:index")
        
    else:
        form = SomeForm()
     
    
    #template = loader.get_template("mangalib/index.html")
    context = {
        "message":"Hello world",
        "newscontent": 15,
        "users":["Vincent", "Laurent", "Jean", "Isaac"],
        "books" : Book.objects.all().order_by("title") ,
        "form" : form
        }
    return render(request, "mangalib/index.html", context)

def show(request, book_id):
    context = {
        "book" : get_object_or_404(Book, pk=book_id)
    }
    
    return render(request,  "mangalib/book.html", context)

def add(request):
    author = Author.objects.get(name = "Akira Toriyama")
    book = Book.objects.create(title = "Dragon Quest", quantity=13, author=author)
    return redirect("mangalib:index")

tp/1/first/mangalib/templates/mangalib/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{book.title}}</title>
    <link rel="stylesheet" href="{% static 'globals.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
    
</head>
<body>
    <h1>{{ book.title }}</h1>
    <p>Quantité : {{ book.quantity }}</p>
    <p>Autheur : {{book.author.name}}</p>
    <p><a href="{% url 'mangalib:index' %}">&laquo; Revenir a la liste</a></p>
</body>
</html>

tp/1/first/mangalib/templates/mangalib/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'globals.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
    
</head>
<body>
   
    <div class="container">
        <div class="fir">
            <p>
                <h1>Bienvenue sur mangalib</h1>

            </p>
            <p>
                {{message}}
            </p>

            <form method="post">
                {% csrf_token %}

                {{ form.as_p }}
                <input type="submit" value="Send">
            </form>
            <p>
                <a href="#">xxx</a>
            </p>
        </div>
        {% lorem 2 p %} 
        <!--{% debug %} -->
        {% now "d/m/y H:i:s" %}
        <h2>
            contenu d'un autre fichier
        </h2>
        {% include  "./other.html" %}
        
        {% if newscontent >= 1 %}
            <p>Il a {{ newscontent }} new{{ newscontent | pluralize }} {{ var }}disponible</p>
        {% else %}
        <p>Pas de news Dispo</p>
        {% endif %} 

        <p>
            {% for u in users %}
            <li>
                {{ u }}
            </li>
            {% endfor %}
        </p>
        <p>
            {{ users | random    }}
        </p>
        <table>
            <tr>
                <th>Nom</th>
                <th>Auteur</th>
                <th>Qté</th>
                <th colspan="2">Actions</th>
            </tr>
            {% for book in books %}
            <tr>
                
                    <td><a href="{% url 'mangalib:show' book.id %}">{{ book.title }}</a></td>
                    
                    <td>{{ book.author }}</td>
                    <td>{{ book.quantity }}</td>
                    <td><a href="">edit</a></td>
                    <td><a href="">Del</a></td>
                
            </tr>
            {% endfor %}
        </table>
    </div>
    <p>
        <a href="{% url 'mangalib:add' %}">[+]</a>
    </p>
</body>
</html>

tp/1/first/mangalib/templates/mangalib/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>bla bla bla</li>
        <li>{% lorem 6 w random %}</li>
    </ul>
</body>
</html>